use_default_settings: true

general:
  instance_name: mmt-local-search

search:
  formats:
    - html
    - json

server:
  bind_address: 0.0.0.0
  port: 8080
  limiter: false
  image_proxy: false
  secret_key: "replace-this-local-dev-secret"
